# Generated by Django 4.2.21 on 2025-06-04 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationuser',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
