# Generated by Django 4.2.7 on 2025-06-04 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_api', '0003_alter_call_capacity_alter_course_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='end_date',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
