# Generated by Django 4.2.22 on 2025-06-04 22:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_api', '0004_alter_group_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupstudent',
            name='feedback',
            field=models.PositiveIntegerField(blank=True, help_text='Feedback rating from 1 to 10', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='group',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
